Update GitHub Actions workflow to check for TAURI_KEY_PASSWORD: Modify error handling to ensure the build process fails if TAURI_KEY_PASSWORD is not set, enhancing clarity in the error message.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -48,10 +48,11 @@ jobs:
             - uses: actions/checkout@v4
 
             - name: Check Tauri
-              if: ${{ !secrets.TAURI_KEY_PASSWORD }}
               run: |
-                  echo "::error::TAURI_PRIVATE_KEY is required"
-                  exit 1
+                  if [ -z "${{ secrets.TAURI_KEY_PASSWORD }}" ]; then
+                    echo "::error::TAURI_KEY_PASSWORD is required but not set."
+                    exit 1
+                  fi
 
             - name: Install rust target
               run: rustup target add ${{ matrix.target }}
